import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from services.analytics import calculate_analytics
from services.forecast import generate_forecast
from services.insights import generate_insights

# Custom canvas for page numbering and header/footer accents
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_number(self, page_count):
        # Draw header bar and page number (except page 1)
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#6B7280"))
        
        # Primary Color: #1E3A8A (Navy)
        primary_color = colors.HexColor("#1E3A8A")
        
        if self._pageNumber > 1:
            # Running Header
            self.setStrokeColor(colors.HexColor("#E5E7EB"))
            self.setLineWidth(0.5)
            self.line(54, 738, 558, 738)
            self.drawString(54, 744, "BANK STATEMENT ANALYZER - FINANCIAL INTELLIGENCE REPORT")
            
            # Running Footer
            self.line(54, 54, 558, 54)
            page_text = f"Page {self._pageNumber} of {page_count}"
            self.drawRightString(558, 42, page_text)
            self.drawString(54, 42, "CONFIDENTIAL - PROCESSED SECURELY")
            
            # Left accent block
            self.setFillColor(primary_color)
            self.rect(54, 738, 10, 4, fill=True, stroke=False)
        else:
            # Cover page running footer only
            self.drawCentredString(306, 42, "Generated by Bank Statement Analyzer. No cloud data retained.")
            
        self.restoreState()

def generate_pdf_report(dest_path, report_type="Summary", date_range="All Time", selected_sections=None, start_date=None, end_date=None):
    """
    Builds a styled ReportLab PDF report.
    report_type: "Summary", "Detailed", "Analytics", "Custom"
    """
    analytics = calculate_analytics(start_date, end_date)
    kpis = analytics["kpis"]
    category_spending = analytics["category_spending"]
    top_merchants = analytics["top_merchants"]
    top_contacts = analytics["top_contacts"]
    subscriptions = analytics["subscriptions"]
    
    forecast = generate_forecast(start_date=start_date, end_date=end_date)
    insights = generate_insights(analytics)
    
    # Document Setup (0.75 in margins: 54 points)
    doc = SimpleDocTemplate(
        dest_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    styles = getSampleStyleSheet()
    
    # Design Tokens (Harmonious Blues and Grays)
    NAVY = colors.HexColor("#1E3A8A")
    SLATE = colors.HexColor("#475569")
    LIGHT_GRAY = colors.HexColor("#F8FAFC")
    BORDER_GRAY = colors.HexColor("#E2E8F0")
    SUCCESS_GREEN = colors.HexColor("#10B981")
    WARNING_GOLD = colors.HexColor("#F59E0B")
    
    # Custom Paragraph Styles
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=28,
        leading=34,
        textColor=NAVY,
        spaceAfter=10
    )
    
    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        leading=18,
        textColor=SLATE,
        spaceAfter=30
    )
    
    h1_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=NAVY,
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    h2_style = ParagraphStyle(
        'SubsectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=SLATE,
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#1F2937"),
        spaceAfter=8
    )
    
    table_cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#1F2937")
    )
    
    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=table_cell_style,
        fontName='Helvetica-Bold',
        textColor=colors.white
    )
    
    insight_style = ParagraphStyle(
        'InsightStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor("#111827"),
        spaceAfter=4
    )
    
    story = []
    
    # ------------------ COVER PAGE ------------------
    story.append(Spacer(1, 1.5 * inch))
    story.append(Paragraph("Financial Intelligence Report", title_style))
    
    report_name_map = {
        "Summary": "Executive Summary & Category Analysis",
        "Detailed": "Comprehensive Statement & Transaction Audit",
        "Analytics": "In-Depth Financial Analytics & Heatmaps",
        "Custom": "Tailored Financial Performance Insights"
    }
    story.append(Paragraph(report_name_map.get(report_type, "Financial Summary"), subtitle_style))
    story.append(Spacer(1, 0.5 * inch))
    
    # Cover Metadata Block
    meta_data = [
        [Paragraph("<b>Period:</b>", body_style), Paragraph(date_range, body_style)],
        [Paragraph("<b>Account Holder:</b>", body_style), Paragraph(analytics.get("account_holder", "Manas Purnendu"), body_style)],
        [Paragraph("<b>Generated On:</b>", body_style), Paragraph(datetime.now().strftime("%d %b %Y, %I:%M %p"), body_style)],
        [Paragraph("<b>Status:</b>", body_style), Paragraph("Final Draft", body_style)]
    ]
    meta_table = Table(meta_data, colWidths=[1.5*inch, 3.5*inch])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('TOPPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(meta_table)
    
    story.append(Spacer(1, 2 * inch))
    story.append(PageBreak())
    
    # Check default section visibility
    if selected_sections is None:
        selected_sections = ["kpis", "spending", "insights", "subscriptions", "forecasts"]
        if report_type == "Detailed":
            selected_sections.append("transactions")
        elif report_type == "Analytics":
            selected_sections.extend(["merchants", "contacts"])
            
    # ------------------ SECTION 1: KEY PERFORMANCE INDICATORS ------------------
    if "kpis" in selected_sections:
        story.append(Paragraph("1. Executive Financial KPIs", h1_style))
        story.append(Paragraph(
            "The following metrics summarize the core cash flow dynamics calculated from the parsed statement data. "
            "Net savings represent total credited funds minus debited outflows.",
            body_style
        ))
        story.append(Spacer(1, 5))
        
        # Draw a table of KPIs
        kpi_table_data = [
            [
                Paragraph("<b>Current Balance</b>", table_cell_style), 
                Paragraph(f"\u20b9 {kpis['balance']:,.2f}", table_cell_style),
                Paragraph("<b>Total Income</b>", table_cell_style), 
                Paragraph(f"\u20b9 {kpis['income']:,.2f}", table_cell_style)
            ],
            [
                Paragraph("<b>Total Expenses</b>", table_cell_style), 
                Paragraph(f"\u20b9 {kpis['expense']:,.2f}", table_cell_style),
                Paragraph("<b>Net Savings</b>", table_cell_style), 
                Paragraph(f"\u20b9 {kpis['savings']:,.2f}", table_cell_style)
            ],
            [
                Paragraph("<b>Savings Rate</b>", table_cell_style), 
                Paragraph(f"{kpis['savings_rate']:.1f}%", table_cell_style),
                Paragraph("<b>Busiest Day</b>", table_cell_style), 
                Paragraph(f"{kpis['busiest_day']} (\u20b9 {kpis['busiest_day_amount']:,.0f})", table_cell_style)
            ]
        ]
        kpi_table = Table(kpi_table_data, colWidths=[1.25*inch, 1.25*inch, 1.25*inch, 1.25*inch])
        kpi_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), LIGHT_GRAY),
            ('BOX', (0,0), (-1,-1), 1, BORDER_GRAY),
            ('INNERGRID', (0,0), (-1,-1), 0.5, BORDER_GRAY),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 8),
            ('RIGHTPADDING', (0,0), (-1,-1), 8),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(kpi_table)
        story.append(Spacer(1, 20))

    # ------------------ SECTION 2: SPENDING BY CATEGORY ------------------
    if "spending" in selected_sections and category_spending:
        story.append(Paragraph("2. Expense Category Distribution", h1_style))
        story.append(Paragraph("Below is the percentage-wise category distribution of all debits.", body_style))
        story.append(Spacer(1, 5))
        
        spending_table_data = [[
            Paragraph("Category Name", table_header_style), 
            Paragraph("Total Outflow", table_header_style), 
            Paragraph("Percentage", table_header_style)
        ]]
        
        for item in category_spending:
            spending_table_data.append([
                Paragraph(item["category_name"], table_cell_style),
                Paragraph(f"\u20b9 {item['amount']:,.2f}", table_cell_style),
                Paragraph(f"{item['percentage']:.1f}%", table_cell_style)
            ])
            
        spending_table = Table(spending_table_data, colWidths=[2.2*inch, 1.5*inch, 1.3*inch])
        spending_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), NAVY),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_GRAY),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_GRAY]),
        ]))
        story.append(spending_table)
        story.append(Spacer(1, 20))

    # ------------------ SECTION 3: MERCHANT & CONTACT ANALYSIS ------------------
    if "merchants" in selected_sections and top_merchants:
        story.append(Paragraph("3. Top 5 Business Merchants", h1_style))
        story.append(Paragraph("These are the commercial entities that received the largest aggregate share of your payments.", body_style))
        
        merchant_table_data = [[
            Paragraph("Merchant Name", table_header_style), 
            Paragraph("Total Outflow", table_header_style), 
            Paragraph("Tx Count", table_header_style),
            Paragraph("Avg. Tx Value", table_header_style)
        ]]
        for m in top_merchants[:5]:
            merchant_table_data.append([
                Paragraph(m["merchant_name"], table_cell_style),
                Paragraph(f"\u20b9 {m['total_spend']:,.2f}", table_cell_style),
                Paragraph(str(m['transaction_count']), table_cell_style),
                Paragraph(f"\u20b9 {m['average_transaction_value']:,.2f}", table_cell_style)
            ])
        merchant_table = Table(merchant_table_data, colWidths=[1.8*inch, 1.1*inch, 0.9*inch, 1.2*inch])
        merchant_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), SLATE),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_GRAY),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_GRAY]),
        ]))
        story.append(merchant_table)
        story.append(Spacer(1, 15))
        
    if "contacts" in selected_sections and top_contacts:
        story.append(Paragraph("4. Top 5 Individuals / Payees", h1_style))
        story.append(Paragraph("These represent payments or transfers sent to individual contacts.", body_style))
        
        contact_table_data = [[
            Paragraph("Contact Name", table_header_style), 
            Paragraph("Total Transferred", table_header_style), 
            Paragraph("Tx Count", table_header_style),
            Paragraph("Avg. Transfer Value", table_header_style)
        ]]
        for c in top_contacts[:5]:
            contact_table_data.append([
                Paragraph(c["payee_name"], table_cell_style),
                Paragraph(f"\u20b9 {c['total_spend']:,.2f}", table_cell_style),
                Paragraph(str(c['transaction_count']), table_cell_style),
                Paragraph(f"\u20b9 {c['average_transaction_value']:,.2f}", table_cell_style)
            ])
        contact_table = Table(contact_table_data, colWidths=[1.8*inch, 1.1*inch, 0.9*inch, 1.2*inch])
        contact_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), SLATE),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_GRAY),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_GRAY]),
        ]))
        story.append(contact_table)
        story.append(Spacer(1, 20))

    # ------------------ SECTION 4: SUBSCRIPTION DETECTION ------------------
    if "subscriptions" in selected_sections and subscriptions:
        story.append(Paragraph("5. Recurring Subscriptions", h1_style))
        story.append(Paragraph("The following active monthly, quarterly, or yearly recurring payments were detected.", body_style))
        story.append(Spacer(1, 5))
        
        sub_table_data = [[
            Paragraph("Subscription Merchant", table_header_style), 
            Paragraph("Category", table_header_style), 
            Paragraph("Monthly Cost", table_header_style),
            Paragraph("Frequency", table_header_style),
            Paragraph("Est. Next Payment", table_header_style)
        ]]
        for s in subscriptions:
            sub_table_data.append([
                Paragraph(s["merchant_name"], table_cell_style),
                Paragraph(s["category_name"], table_cell_style),
                Paragraph(f"\u20b9 {s['amount']:,.2f}", table_cell_style),
                Paragraph(s["frequency"], table_cell_style),
                Paragraph(s["next_billing"], table_cell_style)
            ])
        sub_table = Table(sub_table_data, colWidths=[1.5*inch, 1.1*inch, 0.9*inch, 0.75*inch, 1.15*inch])
        sub_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), NAVY),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_GRAY),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_GRAY]),
        ]))
        story.append(sub_table)
        story.append(Spacer(1, 20))

    # ------------------ SECTION 5: FORECASTS ------------------
    if "forecasts" in selected_sections and forecast.get("success"):
        story.append(Paragraph("6. Financial Projections (Next 3 Months)", h1_style))
        story.append(Paragraph(
            "Projections calculated using moving averages and trend rates. "
            "The numbers assume baseline spending patterns are maintained.",
            body_style
        ))
        story.append(Spacer(1, 5))
        
        forecast_table_data = [[
            Paragraph("Month", table_header_style), 
            Paragraph("Projected Income", table_header_style), 
            Paragraph("Projected Outflow", table_header_style),
            Paragraph("Projected Savings", table_header_style),
            Paragraph("Savings Rate", table_header_style)
        ]]
        for f in forecast["forecast_details"]:
            forecast_table_data.append([
                Paragraph(f["month"], table_cell_style),
                Paragraph(f"\u20b9 {f['projected_income']:,.2f}", table_cell_style),
                Paragraph(f"\u20b9 {f['projected_expense']:,.2f}", table_cell_style),
                Paragraph(f"\u20b9 {f['projected_savings']:,.2f}", table_cell_style),
                Paragraph(f"{f['savings_rate']:.1f}%", table_cell_style)
            ])
            
        # Add summary row
        forecast_table_data.append([
            Paragraph("<b>Total (3 Months)</b>", table_cell_style),
            Paragraph(f"<b>\u20b9 {forecast['kpis']['projected_income']:,.2f}</b>", table_cell_style),
            Paragraph(f"<b>\u20b9 {forecast['kpis']['projected_expense']:,.2f}</b>", table_cell_style),
            Paragraph(f"<b>\u20b9 {forecast['kpis']['projected_savings']:,.2f}</b>", table_cell_style),
            Paragraph(f"<b>{forecast['kpis']['savings_rate']:.1f}%</b>", table_cell_style)
        ])
        
        forecast_table = Table(forecast_table_data, colWidths=[0.9*inch, 1.1*inch, 1.1*inch, 1.1*inch, 0.8*inch])
        forecast_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), NAVY),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_GRAY),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('ROWBACKGROUNDS', (0,1), (-1,-2), [colors.white, LIGHT_GRAY]),
            ('BACKGROUND', (0,-1), (-1,-1), colors.HexColor("#EFF6FF")), # highlighted sum row
        ]))
        story.append(forecast_table)
        story.append(Spacer(1, 20))

    # ------------------ SECTION 6: INSIGHTS & RECOMMENDATIONS ------------------
    if "insights" in selected_sections and insights:
        story.append(Paragraph("7. Financial Intelligence & Recommendations", h1_style))
        story.append(Paragraph("Below are rule-based system suggestions generated based on your spending behavior:", body_style))
        story.append(Spacer(1, 5))
        
        insights_box_data = []
        for i in insights:
            color_accent = SUCCESS_GREEN if i["status"] == "success" else (WARNING_GOLD if i["status"] == "warning" else NAVY)
            p_text = f"<b>[{i['type'].upper()}]</b> {i['text']}"
            insights_box_data.append([
                Paragraph(f"<font color='{color_accent.hexval()}'>\u25cf</font>", title_style), # dot indicator
                Paragraph(p_text, insight_style)
            ])
            
        insights_table = Table(insights_box_data, colWidths=[0.2*inch, 4.8*inch])
        insights_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(insights_table)
        
    # Build Document
    doc.build(story, canvasmaker=NumberedCanvas)
