#!/usr/bin/env python3
"""Database migration script (v3) to add users table and ensure user_id columns are present.
Run with: python -m database.v3_migrations
"""
import sqlite3
import os
from datetime import datetime, timedelta

# Path to the SQLite DB (same as in db.py)
DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'bank_statement.db')

def enable_foreign_keys(conn):
    conn.execute('PRAGMA foreign_keys = ON')

def create_users_table(conn):
    conn.execute('''
        CREATE TABLE IF NOT EXISTS users (
            user_id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'user',
            failed_attempts INTEGER DEFAULT 0,
            locked_until DATETIME
        )
    ''')
    conn.commit()
    print('Created users table')

def seed_default_admin(conn, email='admin@example.com', password_hash=''):
    # If a password hash is provided, insert admin; otherwise skip.
    if not password_hash:
        return
    try:
        conn.execute('INSERT INTO users (email, password_hash, role) VALUES (?, ?, ?)',
                     (email, password_hash, 'admin'))
        conn.commit()
        print(f'Seeded default admin user: {email}')
    except sqlite3.IntegrityError:
        print('Default admin already exists')

def add_user_id_columns(conn):
    # statements table
    cur = conn.execute('PRAGMA table_info(statements)')
    cols = [row[1] for row in cur.fetchall()]
    if 'user_id' not in cols:
        conn.execute('ALTER TABLE statements ADD COLUMN user_id INTEGER')
        conn.commit()
        print('Added user_id to statements')
    else:
        print('user_id already in statements')

    # transactions table
    cur = conn.execute('PRAGMA table_info(transactions)')
    cols = [row[1] for row in cur.fetchall()]
    if 'user_id' not in cols:
        conn.execute('ALTER TABLE transactions ADD COLUMN user_id INTEGER')
        conn.commit()
        print('Added user_id to transactions')
    else:
        print('user_id already in transactions')

def create_indexes(conn):
    conn.execute('CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)')
    conn.execute('CREATE INDEX IF NOT EXISTS idx_statements_user_id ON statements(user_id)')
    conn.execute('CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id)')
    conn.commit()
    print('Indexes created')

def main():
    conn = sqlite3.connect(DB_PATH)
    enable_foreign_keys(conn)
    create_users_table(conn)
    # Optionally seed an admin (hash should be generated by the app; placeholder here)
    # seed_default_admin(conn, email='admin@example.com', password_hash='')
    add_user_id_columns(conn)
    create_indexes(conn)
    conn.close()
    print('Migration v3 completed')

if __name__ == '__main__':
    main()
